### ISSUE TITLE
Access to 'google.com' from origin 'http://localhost:8000' has been blocked by CORS

### ISSUE THREAD

**Issue by websharik** [fonoster/routr-ui#11]
Im run router in docker, inslall cli and run proxy. First seconds i see panels then app start ping google and goOffline.

**Comment by mc256** [comment]
I am having the same issue
```
Access to XMLHttpRequest at 'https://google.com/' from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by psanders** [comment]
@mc256 @websharik 

We will have a fix for this soon.

**Comment by psanders** [comment]
We are all set here. Please try again with the latest version of [routr-ctl.](https://www.npmjs.com/package/routr-ctl)

**Comment by mc256** [comment]
It works! Thanks!

**Comment by Lizz850517** [comment]
@websharik @mc256  Hi, sorry to bother!
I run routr in docker on my mac,
i have no clue where to install the rctl and where to run rctl proxy to entering the web consle
could you please tell me what step should i go through?
